# NumPy ile Lineer Cebir



Asagidaki satirlari calistirarak en altta yer alan odev sorularini yaptiktan sonra dosyanin adini 

ad_soyad_ogrencino 

seklinde degistirerek en gec 18 Subat 23:59'a kadar

[bu adrese](https://stdyildizedu-my.sharepoint.com/:f:/g/personal/sbedir_fbe_yildiz_edu_tr/EtMqKYz3ktxIl16Sh4vGEtIBaA6a3-6uw0nyFtqwNyiCGw) yukleyiniz.

In [45]:
import numpy as np

## NumPy Arrayleri

1D NumPy array bir sayi listesi gibi dusunulebilir. 
2D NumPy arrayleri matrislere karsilik gelir. 
2D NumPy arrayden bir satir veya sutun secersek, sonuc bir 1D NumPy array olur([slice](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#basic-slicing-and-indexing)). 

Karisiklik olmamasi icin her zaman NumPy arraylerimizin tipi(shape), girdi sayisi (size) ve boyutu (dimension) takip edilmelidir.

### Array Attributes

1D (one-dimensional) bir NumPy array olusturup tipi(shape), girdi sayisi (size) ve boyutu (dimension) niteliklerini inceleyelim

In [46]:
a = np.array([1,3,-2,1])
print(a)

[ 1  3 -2  1]


In [47]:
a.ndim

1

In [48]:
a.shape

(4,)

In [97]:
#Deneme1

a.shape[0]

4

In [49]:
a.size

4

2D (two-dimensional) NumPy array (matris) olusturalim:

In [50]:
M = np.array([[1,2],[3,7],[-1,5]])
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


In [51]:
M.ndim

2

In [52]:
M.shape

(3, 2)

In [98]:
#Deneme

M.shape[1]

2

In [53]:
M.size

6

2D NumPy array'den bir satir veya sutun secelim:

In [54]:
col = M[:,1] # M'nin tum satirlarini ve 1.sutununu iceren elemanlar listesini getirir
print(col)

[2 7 5]


In [55]:
col.ndim

1

In [56]:
col.shape

(3,)

In [57]:
col.size

3

Sectigimiz listenin bir sutun vektoru gibi davranmasi icin [reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) metodunu kullanmaliyiz 

In [58]:
print(col)

[2 7 5]


In [59]:
column = np.array([2,7,5]).reshape(3,1)
print(column)

[[2]
 [7]
 [5]]


In [60]:
print('Dimensions:', column.ndim)
print('Shape:', column.shape)
print('Size:', column.size)

Dimensions: 2
Shape: (3, 1)
Size: 3


Ayni icerige sahip olmalarina ragmen `col` ve `column` degiskenleri farkli tipte objelerdir.

In [61]:
print(col)

[2 7 5]


In [62]:
print('Dimensions:',col.ndim)
print('Shape:',col.shape)
print('Size:',col.size)

Dimensions: 1
Shape: (3,)
Size: 3


## Matrislerde Islemler



NumPy arraylerde `+`, `-`, `/`, `*` ve `**` islemleri eleman elemana yapilir.

In [63]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [64]:
M * M

array([[ 9, 16],
       [ 1, 25]])

### Matris Carpimi

NumPy arraylerde matris carpimi icin `@` operatoru kullanilir.

In [65]:
M @ M

array([[ 5, 32],
       [-8, 21]])

In [66]:
col @ column

array([78])

### Birim Matris

In [67]:
I = np.eye(2) #2x2 birim matrisi olusturur.

In [68]:
print(I)

[[1. 0.]
 [0. 1.]]


Simdi 

$$
A = \begin{bmatrix}
1 & 3 \\\
-1 & 7
\end{bmatrix}
\ \ \ \
B = \begin{bmatrix}
5 & 2 \\\
1 & 2
\end{bmatrix}
$$

ve $I$ 2x2 birim matris olmak uzere $2I + 3A - AB$'yi hesaplayalim:

In [69]:
A = np.array([[1,3],[-1,7]])
print(A)

[[ 1  3]
 [-1  7]]


In [70]:
B = np.array([[5,2],[1,2]])
print(B)

[[5 2]
 [1 2]]


In [71]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [72]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

In [194]:
A@A

array([[-2, 24],
       [-8, 46]])

In [ ]:
#Deneme


### Matris Kuvvetleri

In [73]:
from numpy.linalg import matrix_power as mpow

In [74]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [181]:
#Deneme

print(M.shape[1])

2


In [75]:
mpow(M,2)

array([[ 5, 32],
       [-8, 21]])

In [76]:
mpow(M,5)

array([[-1525,  3236],
       [ -809,    93]])

In [77]:
M @ M @ M @ M @ M

array([[-1525,  3236],
       [ -809,    93]])

In [78]:
mpow(M,3)

array([[-17, 180],
       [-45,  73]])

In [79]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

###  Transpoz

In [80]:
print(M)

[[ 3  4]
 [-1  5]]


In [489]:
print(M.T)

[[ 3 -1]
 [ 4  5]]


In [82]:
M @ M.T

array([[25, 17],
       [17, 26]])

### Trace (Iz)

In [83]:
np.trace(A)

8

In [84]:
N = np.random.randint(0,10,[2,2])
print(N)

[[1 1]
 [4 6]]


## Odev Sorulari

1. Girdi parametreleri $A$, $i$ ve $j$ olan ve sonuc olarak $A$'nin $i$. ve $j$. satirlarinin ic carpimini donduren bir fonksiyon yaziniz (indexleme 0'dan baslar).
2. $A = \begin{bmatrix} 3 & 4 \\\ -1 & 2 \end{bmatrix}$ ve $B = \begin{bmatrix} 5 & 2 \\\ 8 & -3 \end{bmatrix}$ olmak uzere $AB + 2B^2 - I$ yi hesaplayiniz.
3. Ustteki N matrisi gibi random ureteceginiz bir $4x4$luk $N$ matrisi icin, 
    
    a.) print(N) ile $N$'yi yazdiriniz ve $N$'nin izini bulunuz.
    
    b.) $NN^T$ sonucunu bulunuz.
    
    c.) $NN^T$ sonucu olan matrisin 1. ve 3. satirlarinin ic carpimini 1.soruda yazdiginiz fonksiyonu kullanarak bulunuz.

In [680]:
def satir_ic_carpim(A,i,j):
    # Eger i satir indexi disinda olursa hata dondurmeli: Satir indexi 0'dan baslar, A.shape[0]-1'e kadar gider.
    # A.shape = (2,2) ise A.shape[0] = 2yi verir. A.shape[1] = 2yi verir.
    # i= satır ve j= sütun sayısı için
    if  (i>A.shape[0] or i<0):
        return "i matris satir indeksi disinda! lutfen i icin gecerli bir deger seciniz."
    # Eger j sutun indexi disinda olursa hata dondurmeli: Sutun indexi 0'dan baslar, A.shape[1]-1'e kadar gider.
    elif (j>A.shape[1] or j<0 ):
        return "j matris sutun indeksi disinda! lutfen j icin gecerli bir deger seciniz."
    # Tek satir kodla
        # A'nin i.satirini secmeli
        # A'nin j.satirini secip sutun matrisine cevirmeli: 
        # Bu ikisinin matris carpimini bulmali
    # Sonucu tamsayiya cevirmelisiniz. (int(deger) deger'i tamsayiya cevirir)
   
    else:
        
        result = A[i]@A[j].T
        
                
        return int(result)
    
    
    
A = np.array([[3,4],[-1,8]])
    ## Asagidakileri yaparak fonksiyonunuzun dogrulugunu kontrol ediniz.

In [681]:
A

array([[ 3,  4],
       [-1,  8]])

In [682]:
satir_ic_carpim(M,-1,1)

'i matris satir indeksi disinda! lutfen i icin gecerli bir deger seciniz.'

In [683]:
satir_ic_carpim(M,3,1)

'i matris satir indeksi disinda! lutfen i icin gecerli bir deger seciniz.'

In [684]:
satir_ic_carpim(M,1,-1)

'j matris sutun indeksi disinda! lutfen j icin gecerli bir deger seciniz.'

In [685]:
satir_ic_carpim(M,1,3)

'j matris sutun indeksi disinda! lutfen j icin gecerli bir deger seciniz.'

In [686]:
satir_ic_carpim(M,1,1)

65

In [687]:
#Deneme

satir_ic_carpim(M,0,1)

29

#####################################################################

In [688]:
#2.sorunun Cevabi:

A = np.array([[3,4],[-1,2]])
B = np.array([[5,2],[8,-3]])

I= np.eye(2) #I 2x2lik birim matris

print(A@B +2*mpow(B,2)+(-1*I))
#print(A@B +2*(B@B)+(-1*I)) şeklinde de yazılabilir.



[[128.   2.]
 [ 43.  41.]]


#####################################################################

In [689]:
#3.sorunun Cevabi:
#a
N = np.random.randint(0,10,[4,4])
print(N)
print("\n")

print("Trace of N: ",np.trace(N))




[[6 3 2 7]
 [0 2 8 8]
 [1 9 8 9]
 [5 3 7 7]]


Trace of N:  23


In [690]:
#b
nnt= N@N.T
print(nnt)

[[ 98  78 112 102]
 [ 78 132 154 118]
 [112 154 227 151]
 [102 118 151 132]]


In [691]:
#c

satir_ic_carpim(N,1,3)

118